account/urls.py
from . import views
from django.urls import path

app_name = "account"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path("profile/<int:user_id>/", views.UserProfileView.as_view(), name="user_profile"),
    path("reset/", views.UserPasswordResetView.as_view(), name="reset_password"),
    path("reset/done/", views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("confirm/<uidb64>/<token>/", views.UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("confirm/complete", views.UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("follow/<int:user_id>", views.UserFollowView.as_view(), name="user_follow"),
    path("unfollow/<int:user_id>", views.UserUnfollowView.as_view(), name="user_unfollow"),
    path("edit_user/", views.EditUserView.as_view(), name="edit_user")
]

home/urls.py
from . import views
from django.urls import path

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("post/<int:post_id>/<slug:post_slug>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/delete/<int:post_id>/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post/update/<int:post_id>/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path("reply/<int:post_id>/<int:comment_id>/", views.PostAddReplyView.as_view(), name="add_reply"),
    path("like/<int:post_id>", views.PostLikeView.as_view(), name="post_like"),
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account"))
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created", "body"]

    def __str__(self):
        return f"{self.slug} - {self.updated}"

    def get_absolute_url(self):
        return reverse("home:post_detail", args=(self.id, self.slug))

    def likes_count(self):
        return self.plikes.count()

    def user_can_like(self, user):
        user_like = user.ulikes.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ucomments")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pcomments")
    reply = models.ForeignKey("self", on_delete=models.CASCADE, related_name="rcomments", blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.body[:30]}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ulikes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="plikes")

    def __str__(self):
        return f"{self.user} liked {self.post.slug}"

home/forms.py
from django import forms
from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("body",)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "body": forms.Textarea(attrs={"class": "form-control"})
        }


class CommentReplyFrom(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)


class PostSearchForm(forms.Form):
    search = forms.CharField()

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyFrom, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        # posts = Post.objects.order_by("-created")
        posts = Post.objects.all()
        if request.GET.get("search"):
            posts = posts.filter(body__contains=request.GET["search"])
        return render(request, "home/index.html", {"posts": posts, "form": self.form_class})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyFrom

    def setup(self, request, *args, **kwargs):
        # post = Post.objects.get(pk=post_id, slug=post_slug)
        self.post_instance = get_object_or_404(Post, pk=kwargs["post_id"], slug=kwargs["post_slug"])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        return render(request, "home/detail.html",
                      {"post": self.post_instance, "comments": comments, "form": self.form_class,
                       "reply_form": self.form_class_reply, "can_like": can_like})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, "Comment submitted successfully :)", "success")
            return redirect("home:post_detail", self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, "Deleted Successfully", "success")
        else:
            messages.error(request, "Permission Denied", "danger")
        return redirect("home:home")


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, "Permission Denied", "danger")
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, "home/update.html", {"form": form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["body"][:30])
            new_post.save()
            messages.success(request, "Updated Successfully", "success")
            return redirect("home:post_detail", post.id, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, "home/create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["body"][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, "Post Created :D", "success")
            return redirect("home:post_detail", new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyFrom

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, "Reply submitted successfully :)", "success")
        return redirect("home:post_detail", post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Like.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, "You have liked this post before!", "danger")
        else:
            Like.objects.create(post=post, user=request.user)
            messages.success(request, "Post Liked :)", "success")
        return redirect("home:post_detail", post.id, post.slug)

home/templates/home/create.html
{%  extends "base.html" %}

{% block content %}
     <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary"  type="submit" value="Create">
    </form>
{% endblock %}

home/templates/home/detail.html
{% extends "base.html" %}

{% block content %}

        {% if request.user.id == post.user.id %}
            <a href="{% url "home:post_delete" post.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url "home:post_update" post.id %}" class="btn btn-info">Update</a>
        {% endif %}

    <p>posted by  <a href="{% url "account:user_profile" post.user.id %}">{{ post.user }}</a> in {{ post.updated|date:"Y-M" }}</p>
    <div class="card">
        <p>{{ post.body }}</p>
    </div><hr/>

    {% if request.user.is_authenticated %}
        <a href="{% url "home:post_like" post.id %}" class="{% if can_like %} disabled {% endif %}btn btn-success col-md-1">Like {{ post.likes_count }}</a>

        <form action="" method="post"><br>
            {% csrf_token %}
            {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Send"><br/>
        </form><br/>
    {% else %}
        <p class="alert alert-danger">Only logged in users can comment!</p>
    {% endif %}

    <h5>Comments:</h5>

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince}}</p>
            <p class="card-body">{{ comment.body }}</p>

            {% if request.user.is_authenticated %}
                <form action="{% url "home:add_reply" post.id comment.id %}" method="post" style="display: none">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input class="btn btn-primary" type="submit" value="Send"><br/>
                </form>
            {% endif %}

            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <p class="bg-primary p-3 m-2">{{ reply.user }} | {{ reply.created|timesince }}<br/>{{ reply.body }}</p>
                {% endfor %}
            {% endwith %}
        </div><br/>
    {% empty %}
        <p class="alert alert-info">No comments yet!</p>
    {% endfor %}

{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}

{% block content %}

    {% if request.user.is_authenticated %}
        <h6 style="color: navy"><em>Logged in as {{ request.user.username }}</em></h6>
    {% endif %}

    <br><form action="" method="get">
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <br><div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:5 }}</a>
        {% endfor %}
    </div>

{% endblock %}

home/templates/home/update.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Update">
    </form>
{% endblock %}